NaturalCosmetics/NaturalCosmetics/NaturalCosmetics/Models/Cosmetics.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace NaturalCosmetics.Models
{
    public class Cosmetics
    {
        public int Id { get; set; }
        [Required]
        [StringLength(255)]
        public string Name { get; set; }
        [Required]
        [StringLength(255)]
        public decimal Price { get; set; }
        [Required]
        [StringLength(255)]
        public string Detail { get; set; }
        [Required]
        [StringLength(255)]
        public string Img { get; set; }

        [Required]
        [StringLength(255)]
        public bool IsHotItems { get; set; }

        public int TypeId { get; set; }
        public virtual CosmeticsType CosmeticsTypes { get; set; }

    }

}

NaturalCosmetics/NaturalCosmetics/NaturalCosmetics/Models/CosmeticsType.cs
using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace NaturalCosmetics.Models
{
    public class CosmeticsType
    {
        [Key]
        public int TypeId { get; set; }
        [Required]
        [StringLength(255)]
        public string TypeName { get; set; }
        public ICollection<Cosmetics> Cosmetics { get; set; }
        public CosmeticsType()
        {
            Cosmetics = new Collection<Cosmetics>();
        }
    }
}

NaturalCosmetics/NaturalCosmetics/NaturalCosmetics/Controllers/CosmeticsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using NaturalCosmetics.Models;
using NaturalCosmetics.Core.Interface;
using NaturalCosmetics.Data;
using NaturalCosmetics.Interface;
using NaturalCosmetics.ViewModels;

namespace NaturalCosmetics.Controllers
{
    public class CosmeticsController : Controller
    {
        private readonly IShoppingCart _shoppingCart;
        private readonly ICosmeticsRepository _cosmeticsRepository;
        private readonly ICosmeticsTypeRepository _cosmeticsTypeRepository;

        public CosmeticsController(ICosmeticsRepository cosmeticsRepository, ICosmeticsTypeRepository cosmeticsTypeRepository, IShoppingCart shoppingCart)
        {
            _shoppingCart = shoppingCart;
            _cosmeticsRepository = cosmeticsRepository;
            _cosmeticsTypeRepository = cosmeticsTypeRepository;
        }


        public async Task<IActionResult> List(string cosmeticsType)
        {
            var selectedCosmeticsType = !string.IsNullOrWhiteSpace(cosmeticsType) ? cosmeticsType : null;
            var cosmeticsListViewModel = new CosmeticsListViewModel
            {
                Cosmetics = await _cosmeticsRepository.GetCosmetics(selectedCosmeticsType),
                CurrentCosmeticsType = selectedCosmeticsType ?? "All Cosmetics"
            };
            return View(cosmeticsListViewModel);
        }

        [HttpGet("details/{id}")]
        public async Task<IActionResult> ChiTietSP(int id)
        {

            var cosmetics = await _cosmeticsRepository.GetCosmeticsById(id);

            return View(cosmetics);
        }
        public async Task<IActionResult> Makeup(string searchString, string sortOrder)
        {
            var cosmetics = await _cosmeticsRepository.GetAllCosmeticsNameId(searchString,sortOrder);
            return View(cosmetics);
        }
        [HttpGet("{CosmeticsType?}")]
        public async Task<IActionResult> Index(string searchString, string sortOrder)
        {
            var cosmetics = await _cosmeticsRepository.GetAllCosmeticsNameId(searchString, sortOrder);
            return View(cosmetics);
        }
        public IActionResult Blog()
        {
            return View();
        }
        public async Task<IActionResult> Tintuc()
        {
            return View();
        }
        public async Task<IActionResult> Muahang()
        {
            await _shoppingCart.GetShoppingCartItemsAsync();
            var shoppingCartCountTotal = await _shoppingCart.GetCartCountAndTotalAmmountAsync();
            var shoppingCartViewModel = new ShoppingCartViewModel
            {
                ShoppingCart = _shoppingCart,
                ShoppingCartItemsTotal = shoppingCartCountTotal.ItemCount,
                ShoppingCartTotal = shoppingCartCountTotal.TotalAmmount,
            };


            return View(shoppingCartViewModel);
        }
        [HttpPost]
        public async Task<IActionResult> AddToShoppingCart(int cosmeticsId)
        {
            var selectedCosmetics = await _cosmeticsRepository.GetCosmeticsById(cosmeticsId);
            if (selectedCosmetics == null)
            {
                return NotFound();
            }

            await _shoppingCart.AddToCartAsync(selectedCosmetics);

            return RedirectToAction("Muahang");
        }

        [HttpPost]
        public async Task<IActionResult> RemoveFromShoppingCart(int cosmeticsId)
        {
            var selectedCosmetics = await _cosmeticsRepository.GetCosmeticsById(cosmeticsId);
            if (selectedCosmetics == null)
            {
                return NotFound();
            }

            await _shoppingCart.RemoveFromCartAsync(selectedCosmetics);

            return RedirectToAction("Muahang");
        }

        [HttpPost]
        public async Task<IActionResult> RemoveAllCart()
        {
            await _shoppingCart.ClearCartAsync();
            return RedirectToAction("Muahang");
        }
        public async Task<IActionResult> Skincare(string searchString, string sortOrder)
        {
            var cosmetics = await _cosmeticsRepository.GetAllCosmeticsNameId(searchString, sortOrder);
            return View(cosmetics);
        }
        public async Task<IActionResult> Bodycare(string searchString, string sortOrder)
        {
            var cosmetics = await _cosmeticsRepository.GetAllCosmeticsNameId(searchString, sortOrder);
            return View(cosmetics);
        }
        public async Task<IActionResult> Perfume(string searchString, string sortOrder)
        {
            var cosmetics = await _cosmeticsRepository.GetAllCosmeticsNameId(searchString, sortOrder);
            return View(cosmetics);
        }
        public async Task<IActionResult> Hair(string searchString, string sortOrder)
        {
            var cosmetics = await _cosmeticsRepository.GetAllCosmeticsNameId(searchString, sortOrder);
            return View(cosmetics);
        }
    }
}

NaturalCosmetics/NaturalCosmetics/NaturalCosmetics/Views/Cosmetics/Details.cshtml
@model NaturalCosmetics.Models.Cosmetics
@{
    ViewData["Title"] = "Details";
}
@*<div class="breadcumb_area">
    <div class="container">
        <div class="row">
            <div class="col-12">
                <ol class="breadcrumb d-flex align-items-center">
                    <li class="breadcrumb-item"><a href="#">Trang Chủ</a></li>
                    <li class="breadcrumb-item"><a href="#">Dress</a></li>
                    <li class="breadcrumb-item active">Long Dress</li>
                </ol>
                btn
                <a href="#" class="backToHome d-block"><i class="fa fa-angle-double-left"></i> Trở về phân loại</a>
            </div>
        </div>
    </div>
</div>*@



<section class="single_product_details_area section_padding_0_100">
    <div class="container">
        <div class="row">

            <div class="col-12 col-md-6">
                <div class="single_product_thumb">
                    <div id="product_details_slider" class="carousel slide" data-ride="carousel">

                        <ol class="carousel-indicators">
                            <li class="active" data-slide-to="0" style="background-image: url('/images/upload/@Html.DisplayFor(model => model.Img)')">
                            </li>
                            <li data-slide-to="1" style="background-image: url('/images/upload/@Html.DisplayFor(model => model.Img)');" class="">
                            </li>
                            <li data-slide-to="2" style="background-image: url('/images/upload/@Html.DisplayFor(model => model.Img)');" class="">
                            </li>
                            <li data-slide-to="3" style="background-image: url('/images/upload/@Html.DisplayFor(model => model.Img)');" class="">
                            </li>
                        </ol>

                        <div class="carousel-inner">
                            <div class="carousel-item active">
                                <a class="gallery_img" href="~/images/upload/@Html.DisplayFor(model => model.Img)">
                                    <img class="d-block w-100" src="~/images/upload/@Html.DisplayFor(model => model.Img)" alt="First slide">
                                </a>
                            </div>
                            <div class="carousel-item">
                                <a class="gallery_img" href="~/images/upload/@Html.DisplayFor(model => model.Img)">
                                    <img class="d-block w-100" src="~/images/upload/@Html.DisplayFor(model => model.Img)" alt="Second slide">
                                </a>
                            </div>
                            <div class="carousel-item">
                                <a class="gallery_img" href="~/images/upload/@Html.DisplayFor(model => model.Img)">
                                    <img class="d-block w-100" src="~/images/upload/@Html.DisplayFor(model => model.Img)" alt="Third slide">
                                </a>
                            </div>
                            <div class="carousel-item">
                                <a class="gallery_img" href="~/images/upload/@Html.DisplayFor(model => model.Img)">
                                    <img class="d-block w-100" src="~/images/upload/@Html.DisplayFor(model => model.Img)" alt="Fourth slide">
                                </a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>


            <div class="col-12 col-md-6">
                <div class="single_product_desc">

                    <h4 class="title"><a href="#">@Html.DisplayFor(model => model.Name)</a></h4>

                    <h4 class="price">@{var value = String.Format("{0,-5:N0}đ", Model.Price); }@value</h4>

                    <p class="available">Có sẵn: <span class="text-muted"></span></p>

                    <div class="single_product_ratings mb-15">
                        <i class="fa fa-star" aria-hidden="true"></i>
                        <i class="fa fa-star" aria-hidden="true"></i>
                        <i class="fa fa-star" aria-hidden="true"></i>
                        <i class="fa fa-star" aria-hidden="true"></i>
                        <i class="fa fa-star-o" aria-hidden="true"></i>
                    </div>


                    <form class="cart clearfix mb-50 d-flex" method="post">
                        @*<div class="quantity">
                            <span class="qty-minus" onclick="var effect = document.getElementById('qty'); var qty = effect.value; if( !isNaN( qty ) &amp;&amp; qty > 1 ) effect.value--;return false;"><i class="fa fa-minus" aria-hidden="true"></i></span>
                            <input type="number" class="qty-text" id="qty" step="1" min="1" max="12" name="quantity" value="1">
                            <span class="qty-plus" onclick="var effect = document.getElementById('qty'); var qty = effect.value; if( !isNaN( qty )) effect.value++;return false;"><i class="fa fa-plus" aria-hidden="true"></i></span>
                        </div>*@
                        <button type="submit" name="addtocart" value="5" class="btn cart-submit d-block">Thêm vào giỏ hàng</button>
                    </form>

                    <div id="accordion" role="tablist">
                        <div class="card">
                            <div class="card-header" role="tab" id="headingOne">
                                <h6 class="mb-0">
                                    <a data-toggle="collapse" href="#collapseOne" aria-expanded="true" aria-controls="collapseOne" class="">Thông tin</a>
                                </h6>
                            </div>

                            <div id="collapseOne" class="collapse show" role="tabpanel" aria-labelledby="headingOne" data-parent="#accordion" style="">
                                <div class="card-body">
                                    <p>@Html.DisplayFor(model => model.Detail)</p>
                                </div>
                            </div>
                        </div>
                        <div class="card">
                            <div class="card-header" role="tab" id="headingTwo">
                                <h6 class="mb-0">
                                    <a class="collapsed" data-toggle="collapse" href="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">Thông tin giỏ hàng</a>
                                </h6>
                            </div>
                            <div id="collapseTwo" class="collapse" role="tabpanel" aria-labelledby="headingTwo" data-parent="#accordion" style="">
                                @*<div class="card-body">
                                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Explicabo quis in veritatis officia inventore, tempore provident dignissimos nemo, nulla quaerat. Quibusdam non, eos, voluptatem reprehenderit hic nam! Laboriosam, sapiente! Praesentium.</p>
                                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Officia magnam laborum eaque.</p>
                                </div>*@
                            </div>
                        </div>
                        <div class="card">
                            <div class="card-header" role="tab" id="headingThree">
                                <h6 class="mb-0">
                                    <a class="collapsed" data-toggle="collapse" href="#collapseThree" aria-expanded="false" aria-controls="collapseThree">Va &amp; Returns</a>
                                </h6>
                            </div>
                            <div id="collapseThree" class="collapse" role="tabpanel" aria-labelledby="headingThree" data-parent="#accordion" style="">
                                @*<div class="card-body">
                                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Esse quo sint repudiandae suscipit ab soluta delectus voluptate, vero vitae, tempore maxime rerum iste dolorem mollitia perferendis distinctio. Quibusdam laboriosam rerum distinctio. Repudiandae fugit odit, sequi id!</p>
                                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Beatae qui maxime consequatur laudantium temporibus ad et. A optio inventore deleniti ipsa.</p>
                                </div>*@
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

</section>

NaturalCosmetics/NaturalCosmetics/NaturalCosmetics/Views/Cosmetics/Lienlac.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

NaturalCosmetics/NaturalCosmetics/NaturalCosmetics/Views/Cosmetics/List.cshtml
@model CosmeticsListViewModel
@if (Model.Cosmetics?.Count() > 0)
{
    <h1>@Model.CurrentCosmeticsType </h1>
    <div class="row">
        @foreach (var cosmetics in Model.Cosmetics)
        {
            @await Html.PartialAsync("CakeView", cosmetics);
        }
    </div>
}
else
{
    <h1>Bánh</h1>
    <p>Xin lỗi không tìm thấy '@Model.CurrentCosmeticsType' loại sản phẩm. </p>
}

NaturalCosmetics/NaturalCosmetics/NaturalCosmetics/Views/Cosmetics/Makeup.cshtml
@model IEnumerable<CosmeticsDto>
@using System.Collections.Generic;

<section class="top-discount-area d-md-flex align-items-center">
    <!-- Single Discount Area -->
    <div class="single-discount-area">
        <h5>Miễn phí vận chuyển &amp; Trả hàng</h5>
        <h6><a href="#">Mua ngay</a></h6>
    </div>
    <!-- Single Discount Area -->
    <div class="single-discount-area">
        <h5>COD thanh toán, dịch vụ thanh toán tại nhà khi nhận hàng</h5>
        <h6>Áp dụng đối với khách hàng tại khu vực TP.HCM</h6>
    </div>
    <!-- Single Discount Area -->
    <div class="single-discount-area">
        <h5>Khách hàng tại các Tỉnh/Thành khác</h5>
        <h6>Chuyển khoản tài khoản Ngân hàng hoặc Internet Banking trước khi giao hàng</h6>
    </div>
</section>
<!-- ****** Quick View Modal Area Start ****** -->
@foreach (var item in Model)
{
    @if (@item.TypeId == 1)
    {
        <div class="modal fade" id="@item.Id" tabindex="-1" role="dialog" aria-labelledby="quickview" aria-hidden="true">
            <div class="modal-dialog modal-lg modal-dialog-centered" role="document">
                <div class="modal-content">
                    <button type="button" class="close btn" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>

                    <div class="modal-body">
                        <div class="quickview_body">
                            <div class="container">
                                <div class="row">
                                    <div class="col-12 col-lg-5">
                                        <div class="quickview_pro_img">
                                            <img src="~/images/upload/@item.Img" alt="">
                                        </div>
                                    </div>
                                    <div class="col-12 col-lg-7">
                                        <div class="quickview_pro_des">
                                            <h4 class="title">@item.Name</h4>

                                            <div class="top_seller_product_rating mb-15">
                                                <i class="fa fa-star" aria-hidden="true"></i>
                                                <i class="fa fa-star" aria-hidden="true"></i>
                                                <i class="fa fa-star" aria-hidden="true"></i>
                                                <i class="fa fa-star" aria-hidden="true"></i>
                                                <i class="fa fa-star" aria-hidden="true"></i>
                                            </div>
                                            <h5 class="price">@{var value = String.Format("{0,-5:N0}đ", item.Price); }@value</h5>
                                            <p>@item.Name</p>
                                            <a asp-area="" asp-controller="Cosmetics" asp-action="ChiTietSP" asp-route-id="@item.Id">Xem Chi Tiết Sản Phẩm</a>
                                        </div>
                                        <!-- Add to Cart Form -->
                                        <form class="cart" method="post">
                                            @*<div class="quantity">
                                                <span class="qty-minus" onclick="var effect = document.getElementById('qty'); var qty = effect.value; if( !isNaN( qty ) &amp;&amp; qty &gt; 1 ) effect.value--;return false;"><i class="fa fa-minus" aria-hidden="true"></i></span>

                                                <input type="number" class="qty-text" id="qty" step="1" min="1" max="12" name="quantity" value="1">

                                                <span class="qty-plus" onclick="var effect = document.getElementById('qty'); var qty = effect.value; if( !isNaN( qty )) effect.value++;return false;"><i class="fa fa-plus" aria-hidden="true"></i></span>
                                            </div>*@
                                            <button type="submit" name="addtocart" value="5" class="cart-submit">Thêm vào giỏ hàng</button>
                                            <!-- Wishlist -->
                                            <div class="modal_pro_wishlist">
                                                <a href="wishlist.html" target="_blank"><i class="ti-heart"></i></a>
                                            </div>
                                            <!-- Compare -->
                                            <div class="modal_pro_compare">
                                                <a href="compare.html" target="_blank"><i class="ti-stats-up"></i></a>
                                            </div>
                                        </form>

                                        <div class="share_wf mt-30">
                                            <p>Share With Friend</p>
                                            <div class="_icon">
                                                <a href="#"><i class="fa fa-facebook" aria-hidden="true"></i></a>
                                                <a href="#"><i class="fa fa-twitter" aria-hidden="true"></i></a>
                                                <a href="#"><i class="fa fa-pinterest" aria-hidden="true"></i></a>
                                                <a href="#"><i class="fa fa-google-plus" aria-hidden="true"></i></a>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

    }
}
<!-- ****** Quick View Modal Area End ****** -->

<section class="shop_grid_area section_padding_100">
    <div class="container">
        <div class="row">
            <div class="col-12 col-md-4 col-lg-3">
                <div class="shop_sidebar_area">

                    <div class="widget recommended">
                        <h6 class="widget-title mb-30">Sản Phẩm Khác</h6>
                        @{ int i = 0;}
                        @foreach (var item in Model)
                        {
                            if (item.TypeId == 2)
                            {

                                if (i < 3)
                                {
                                    <div class="widget-desc">
                                        <!-- Single Recommended Product -->

                                        <div class="single-recommended-product d-flex mb-30">
                                            <div class="single-recommended-thumb mr-3">
                                                <img src="~/images/upload/@item.Img" alt="">
                                            </div>
                                            <div class="single-recommended-desc">
                                                <h6>@item.Name</h6>
                                                <p>@{var value = String.Format("{0,-5:N0}đ", item.Price); }@value</p>
                                            </div>
                                        </div>

                                    </div>
                                }
                                i++;
                            }
                        }
                    </div>

                </div>
            </div>


            <div class="col-12 col-md-8 col-lg-9">
                <div class="shop_grid_product_area">
                    <div class="row">
                        @foreach (var item in Model)
                        {
                            if (@item.TypeId == 1)
                            {


                                <!-- Single gallery Item -->
                                <div class="col-12 col-sm-6 col-lg-4 single_gallery_item  wow fadeInUpBig" data-wow-delay="0.2s">
                                    <!-- Product Image -->
                                    <div class="product-img">
                                        <img src="~/images/upload/@item.Img" alt="">
                                        <div class="product-quicview">
                                            <a href="#" data-toggle="modal" data-target="#@item.Id"><i class="ti-plus"></i></a>
                                        </div>
                                    </div>
                                    <!-- Product Description -->
                                    <div class="product-description">
                                        <h4 class="product-price">@{var value = String.Format("{0,-5:N0}đ", item.Price); }@value</h4>
                                        <p>@item.Name</p>
                                        <!-- Add to Cart -->
                                        <a href="#" class="add-to-cart-btn">Thêm vào giỏ hàng</a>
                                    </div>
                                </div>
                            }
                        }

                    </div>
                </div>


                <div class="shop_pagination_area wow fadeInUp" data-wow-delay="1.1s">
                    <nav aria-label="Page navigation">
                        <ul class="pagination pagination-sm">
                            <li class="page-item active"><a class="page-link" href="#">01</a></li>
                            <li class="page-item"><a class="page-link" href="#">02</a></li>
                            <li class="page-item"><a class="page-link" href="#">03</a></li>
                        </ul>
                    </nav>
                </div>

            </div>
        </div>
    </div>
</section>

NaturalCosmetics/NaturalCosmetics/NaturalCosmetics/Views/Cosmetics/Muahang.cshtml
@model ShoppingCartViewModel
@{
    ViewData["Title"] = "Cart";
}
<h2>Cart <i class="fa fa-shopping-cart" aria-hidden="true"></i> </h2>

@if (Model.ShoppingCart.ShoppingCartItems?.Count() <= 0)
{
    <br />
    <h6>Giỏ hàng của bạn trống</h6>
    return;
}

<table class="table table-striped">
    <thead>
        <tr>
            <th>Sản phẩm</th>
            <th>Số lượng</th>
            <th>Giá</th>
            <th>Thành tiền</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model.ShoppingCart.ShoppingCartItems)
        {
            <tr>
                <td>@item.Cosmetics.Name</td>
                <td>
                    <form class="d-inline align-middle" asp-action="RemoveFromShoppingCart"
                          asp-controller="Cosmetics"
                          asp-route-cosmeticsId="@item.CosmeticsId"
                          method="post">
                        <button class="btn fa fa-minus fa-small" aria-hidden="true"></button>
                    </form>
                    <span style="padding:1px 10px">@item.Qty</span>
                    <form class="d-inline align-middle" asp-action="AddToShoppingCart"
                          asp-controller="Cosmetics"
                          asp-route-cosmeticsId="@item.CosmeticsId"
                          method="post">
                        <button class="btn fa fa-plus fa-small" aria-hidden="true"></button>
                    </form>
                </td>
                <td>@{var value2 = String.Format("{0,-5:N0}đ", item.Cosmetics.Price); }@value2</td>
                <td>@{var value1 = String.Format("{0,-5:N0}đ", item.Cosmetics.Price+item.Qty); }@value1</td>
            </tr>
        }
    </tbody>
    <tfoot>
        <tr>
            <td colspan="3">Tổng cộng: </td>
            <td>@{var value = String.Format("{0,-5:N0}đ", Model.ShoppingCartTotal); }@value</td>
        </tr>
        <tr style="border:0">
            <td>
                <form asp-action="RemoveAllCart" method="post">
                    <button class="btn btn-link text-dark" asp-action="RemoveAllCart">
                        <i class="fa fa-times" aria-hidden="true"></i>
                        Xóa giỏ hàng
                    </button>
                </form>
            </td>
            <td colspan="2"></td>
            <td class="text-center">
                <a class="btn buy-now-btn float-right" asp-action="checkout" asp-controller="order">
                    <i class="fa fa-check-square-o" aria-hidden="true"></i>
                    Kiểm tra giỏ hàng
                </a>
            </td>
        </tr>
    </tfoot>
</table>